FROM ubuntu:latest
ARG fetcher_env_db_username
ARG fetcher_env_db_password
ARG fetcher_env_db_host
ARG fetcher_env_db_port
ARG fetcher_env_kinesis_stream_name
ARG fetcher_env_capture_from_schema
ARG fetcher_env_capture_from_table
RUN apt-get update -y
RUN apt-get install -y python3-pip python3-dev build-essential
RUN pip3 install --upgrade pip
COPY requirements.txt /tmp
WORKDIR /tmp
RUN pip3 install -r ./requirements.txt
ENTRYPOINT ["python3"]
CMD ["-c", "--user", "$fetcher_env_db_username", "--password", "$fetcher_env_db_password", "--host", "$fetcher_env_db_host", "--port", "$fetcher_env_db_port", "--kinesis-stream-name", "$fetcher_env_kinesis_stream_name", "--capture-from-schema", "$fetcher_env_capture_from_schema", "--capture-from-table", "$fetcher_env_capture_from_table"]